gameshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from inventory import views

urlpatterns = [
    re_path('^$',views.index ,name='index'),
    path('register/', views.register , name='register'),
    path('admin/', admin.site.urls),
    path('inventory/' , include("inventory.urls")),
    path('user_logout/', views.user_logout , name='user_logout')
]

inventory/urls.py
from django.urls import path, re_path
from inventory import views

app_name = 'inventory'
urlpatterns  = [
    re_path(r'(?P<customer_email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<game_type>[A-Za-z0-9]{2,10})/$', views.gamereturn , name="gamereturn"),
    path('addgame/' , views.addgame , name = "addgame"),
    path('addgame/' , views.addgame , name = "addgame"),
    path('game/' , views.game , name = "game"),
    path('assign/' , views.assign , name = "assign"),
    path('signup/' , views.signup , name = "signup"),
    path('customerinfo/' , views.customerinfo , name = "customerinfo"),
    path('gamereturn/' , views.gamereturn , name = "gamereturn"),
    path('user_login/' , views.user_login , name = "user_login"),
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User 

class Customer(models.Model):

        name = models.CharField(max_length = 264)
        email = models.EmailField(max_length = 264 , unique = True )
        phone_num = models.IntegerField( unique = True )


        def __str__(self):
            return self.email

class Game(models.Model):
        game_name = models.CharField(max_length = 100 )
        game_type = models.CharField(max_length = 100 )


        def __str__(self):
            return "%s - %s" % (self.game_name, self.game_type)

class Assign(models.Model):
        customer_phone = models.ForeignKey( Customer, on_delete=models.CASCADE )
        game_name = models.OneToOneField( Game, on_delete=models.CASCADE , primary_key=True)
        current_date = models.DateField(auto_now=True)

        def __str__(self):
            return self.customer_phone.email

inventory/forms.py
from django import forms
from inventory.models import Customer,Game,Assign
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username' , 'email' , 'password')        

class NewCustomerForm(forms.ModelForm):
    class Meta():
        app_label = 'inventory'
        model = Customer
        fields = '__all__'

class AssigningForm(forms.ModelForm):
    class Meta():
        app_label = 'inventory'
        model = Assign
        fields = '__all__'

class AddGameForm(forms.ModelForm):
    class Meta():
        app_label = 'inventory'
        model = Game
        fields = '__all__'

inventory/views.py
from django.shortcuts import render
from inventory.models import Customer,Game,Assign
from inventory.forms import NewCustomerForm,AssigningForm,AddGameForm,UserForm


#special login imports
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request , "index.html")

def user_login(request):

    if request.method == "POST":
        username = request.POST.get("name")
        password = request.POST.get("passwd")

        user = authenticate(username = username , password = password)

        if user:
            if user.is_active:
                login(request , user)
                return customerinfo(request)

            else:
                return HttpResponse("ACCOUNT NOT Active")

        else:
            return HttpResponse("Invaild username and password")

    else:
        return render(request, 'login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return index(request)


def register(request):
     registered = False
     user_form = UserForm()
     if request.method == "POST":
         user_form = UserForm(request.POST)

         if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
         else:
             print(user_form.error)


     return render(request, "register.html" , {'user_form':user_form , 'registered':registered})

def addgame(request):
    form = AddGameForm()
    if request.method == "POST":
        form = AddGameForm(request.POST)

        if form.is_valid():
            form.save(commit = True)
            return game(request)
        else:
            print("Error input Invalid ")

    return render(request , "addGame.html" , {'form':form})

def gamereturn(request , customer_email , game_type):
    Assign.objects.filter(customer_phone__email = customer_email ).filter( game_name__game_type = game_type).delete()
    return game(request)

def game(request):

    game_list = Game.objects.order_by('game_name')
    status = Assign.objects.order_by('game_name')
    game_dict = {'game_info' : game_list , 'status' : status  }

    return render(request , "game.html" , context = game_dict)


def assign(request):
    form = AssigningForm()
    if request.method == "POST":
        form = AssigningForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return game(request)
        else:
            print("Error input Invaild")
    return render(request , "assign.html" , {'form':form})

def signup(request):
    form = NewCustomerForm()

    if request.method == "POST":
        form = NewCustomerForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return customerinfo(request)
        else:
            print("Error from Invaild")

    return render(request , "signup.html" , {'form':form})

def customerinfo(request):
    customer_list = Customer.objects.order_by('name')
    customer_dict = {'customer_info' : customer_list}
    return render(request , "customerinfo.html" , context = customer_dict)

templates/addGame.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}


<div class="jumbotron">
  <div class="row">

    <div class="col-md-4">

      <p></p>
      <h1>Add Game</h1>
      <p></p>
      <form class="form-group" style="align-items:center"  method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>


    <div class="col-md-8">
      <img src="http://www.nag.co.za/wp-content/uploads/2011/09/Battlefield-3-Reveal-GDC-2011-600x337.jpg" alt="image not found">
    </div>

  </div>
</div>


{% endblock %}

templates/assign.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}
<div class="jumbotron">
  <div class="row">

    <div class="col-md-6">

      <p></p>
      <h1>Assign Game</h1>
      <p></p>
      <form class="form-group" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
      </form>
    </div>


    <div class="col-md-6">
      <img src="https://4.imimg.com/data4/GY/MG/ANDROID-25223310/product-500x500.jpeg" alt="image not found">
    </div>

  </div>
</div>
{% endblock %}

templates/customerinfo.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}
<div class="page-header text-center">
  <h1>Customer information</h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Email</th>
    <th scope="col">Phone Number</th>
  </thead>
  {% for customer in customer_info %}
  <tr>
    <th scope="col">{{customer.id}}</th>
    <td>{{customer.name}}</td>
    <td>{{customer.email}}</td>
    <td>{{customer.phone_num}}</td>
  </tr>
  {% endfor %}
</table>


{% endblock %}

templates/game.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}
<div class="page-header text-center">
  <h1>Games</h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Type</th>
    <th scope="col">Status</th>
  </thead>
  {% for game in game_info %}
  <tr>
    <th scope="col">{{game.id}}</th>
    <td>{{game.game_name}}</td>
    <td>{{game.game_type}}</td>
    {% for ass in status %}
    {% if game.game_name == ass.game_name.game_name and game.game_type == ass.game_name.game_type %}
    <td>Assigned -  {{ass.customer_phone.email}}  -  {{ass.current_date}}</td>
    <td> <a href="/inventory/{{ass.customer_phone.email}}/{{ass.game_name.game_type}}" class="btn btn-primary"> Return </a> </td>
    {% endif %}

    {% endfor %}
  </tr>
  {% endfor %}
</table>

{% endblock %}

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Game Shop</title>
  </head>
  <body>
    <div class="container">
        <ul class="nav" style="background-color: #e8ff68">

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:customerinfo' %}"> CustomerInfo </a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:addgame' %}">AddGame</a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:game' %}">Game</a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:assign' %}"> Assign </a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:signup' %}"> SignUp </a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'user_logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <h1>  Welcome {{user.username}}</h1>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link h3" href="http://127.0.0.1:8000/"> Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'register' %}"> Register </a>
          </li>
          <li class="nav-item">
            <a class="nav-link h3" href="{% url 'inventory:user_login' %}"> Login </a>
          </li>
          {% endif %}

        </ul>

        {% block bodyblock %}


        {% endblock %}

    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}


<div class="jumbotron">

  <div class="row">

    <h1 class="text-center">Welcome to Game Shop Inventory project in Django</h1>

    <div class="col-md-12">
      <img src="https://static1.squarespace.com/static/55ef0e29e4b099e22cdc9eea/t/57767ee73e00beb47f65997d/1467383543057/" alt="image not found">
    </div>

  </div>
</div>


{% endblock %}

templates/login.html
{% extends "home.html" %}
{% block bodyblock %}

<div class="jambotron">

  <h1>Please Login Here !</h1>
  <form  action="{% url 'inventory:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="name" placeholder="Enter Username here">
    <label for="password">Password:</label>
    <input type="password" name="passwd" placeholder="Enter password here">
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

</div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank for registering, New Employee!</h1>
  {% else %}
  <div class="row">

    <div class="col-md-6">

      <p></p>
      <h1>Register</h1>
      <p></p>
      <form class="form-group" method="POST">
        {{ user_form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
      </form>
    </div>


    <div class="col-md-6">
      <img src="https://4.imimg.com/data4/GY/MG/ANDROID-25223310/product-500x500.jpeg" alt="image not found">
    </div>

  </div>
  {% endif %}
</div>
{% endblock %}

templates/signup.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% block bodyblock %}
<div class="jumbotron">
  <div class="row">

    <div class="col-md-4">

      <p></p>
      <h1>Lets Sign U Up !</h1>
      <p></p>
      <form class="form-group"  method="POST">

        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">

      </form>
    </div>


    <div class="col-md-8">
      <img src="http://www.lanehartbooks.com/uploads/7/8/1/6/78163430/4007905_orig.png" alt="image not found">
    </div>

  </div>
</div>



{% endblock %}